# -*- coding: utf-8 -*-
from django.conf import settings
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required


from django.shortcuts import render

# Create your views here.


@login_required
def checkout(request):
	publishKey = settings.STRIPE_PUBLISHABLE_KEY

	if request.method == 'POST':
		#store the token generated by stripe to be passed for a charge
		token = request.POST['stripeToken'] 
	context = {'publishKey' : publishKey}
	template = 'checkout.html'
	return render(request, template, context)

